
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.daniel.analizadores;

import com.daniel.*;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int HEAD_ARROW = 7;
  public static final int PIPE = 13;
  public static final int SEMICOLON = 16;
  public static final int PERCENT = 8;
  public static final int PLUS = 11;
  public static final int RBRACE = 4;
  public static final int DIGIT = 21;
  public static final int STAR = 10;
  public static final int IDENTIFIER = 20;
  public static final int COLON = 5;
  public static final int LBRACE = 3;
  public static final int TILDE = 14;
  public static final int STRING_LITERAL = 22;
  public static final int LOWERCASE = 18;
  public static final int ESCAPE_SEQUENCE = 17;
  public static final int BODY_ARROW = 6;
  public static final int COMMA = 15;
  public static final int EOF = 0;
  public static final int CONJ = 2;
  public static final int error = 1;
  public static final int DOT = 9;
  public static final int UPPERCASE = 19;
  public static final int ASCII = 23;
  public static final int QUERY = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONJ",
  "LBRACE",
  "RBRACE",
  "COLON",
  "BODY_ARROW",
  "HEAD_ARROW",
  "PERCENT",
  "DOT",
  "STAR",
  "PLUS",
  "QUERY",
  "PIPE",
  "TILDE",
  "COMMA",
  "SEMICOLON",
  "ESCAPE_SEQUENCE",
  "LOWERCASE",
  "UPPERCASE",
  "IDENTIFIER",
  "DIGIT",
  "STRING_LITERAL",
  "ASCII"
  };
}

